// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: scram.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScramAuthenticator_GetCredential_FullMethodName = "/proto.ScramAuthenticator/GetCredential"
)

// ScramAuthenticatorClient is the client API for ScramAuthenticator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScramAuthenticatorClient interface {
	GetCredential(ctx context.Context, in *LoadCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
}

type scramAuthenticatorClient struct {
	cc grpc.ClientConnInterface
}

func NewScramAuthenticatorClient(cc grpc.ClientConnInterface) ScramAuthenticatorClient {
	return &scramAuthenticatorClient{cc}
}

func (c *scramAuthenticatorClient) GetCredential(ctx context.Context, in *LoadCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, ScramAuthenticator_GetCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScramAuthenticatorServer is the server API for ScramAuthenticator service.
// All implementations must embed UnimplementedScramAuthenticatorServer
// for forward compatibility.
type ScramAuthenticatorServer interface {
	GetCredential(context.Context, *LoadCredentialRequest) (*GetCredentialResponse, error)
	mustEmbedUnimplementedScramAuthenticatorServer()
}

// UnimplementedScramAuthenticatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScramAuthenticatorServer struct{}

func (UnimplementedScramAuthenticatorServer) GetCredential(context.Context, *LoadCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedScramAuthenticatorServer) mustEmbedUnimplementedScramAuthenticatorServer() {}
func (UnimplementedScramAuthenticatorServer) testEmbeddedByValue()                            {}

// UnsafeScramAuthenticatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScramAuthenticatorServer will
// result in compilation errors.
type UnsafeScramAuthenticatorServer interface {
	mustEmbedUnimplementedScramAuthenticatorServer()
}

func RegisterScramAuthenticatorServer(s grpc.ServiceRegistrar, srv ScramAuthenticatorServer) {
	// If the following call pancis, it indicates UnimplementedScramAuthenticatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScramAuthenticator_ServiceDesc, srv)
}

func _ScramAuthenticator_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScramAuthenticatorServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScramAuthenticator_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScramAuthenticatorServer).GetCredential(ctx, req.(*LoadCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScramAuthenticator_ServiceDesc is the grpc.ServiceDesc for ScramAuthenticator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScramAuthenticator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ScramAuthenticator",
	HandlerType: (*ScramAuthenticatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredential",
			Handler:    _ScramAuthenticator_GetCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scram.proto",
}
