// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: scram.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Storeinfo     string                 `protobuf:"bytes,1,opt,name=storeinfo,proto3" json:"storeinfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadCredentialRequest) Reset() {
	*x = LoadCredentialRequest{}
	mi := &file_scram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadCredentialRequest) ProtoMessage() {}

func (x *LoadCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadCredentialRequest.ProtoReflect.Descriptor instead.
func (*LoadCredentialRequest) Descriptor() ([]byte, []int) {
	return file_scram_proto_rawDescGZIP(), []int{0}
}

func (x *LoadCredentialRequest) GetStoreinfo() string {
	if x != nil {
		return x.Storeinfo
	}
	return ""
}

type GetCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCredentialResponse) Reset() {
	*x = GetCredentialResponse{}
	mi := &file_scram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCredentialResponse) ProtoMessage() {}

func (x *GetCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetCredentialResponse) Descriptor() ([]byte, []int) {
	return file_scram_proto_rawDescGZIP(), []int{1}
}

func (x *GetCredentialResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetCredentialResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_scram_proto protoreflect.FileDescriptor

const file_scram_proto_rawDesc = "" +
	"\n" +
	"\vscram.proto\x12\x05proto\"5\n" +
	"\x15LoadCredentialRequest\x12\x1c\n" +
	"\tstoreinfo\x18\x01 \x01(\tR\tstoreinfo\"O\n" +
	"\x15GetCredentialResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword2a\n" +
	"\x12ScramAuthenticator\x12K\n" +
	"\rGetCredential\x12\x1c.proto.LoadCredentialRequest\x1a\x1c.proto.GetCredentialResponseB@Z>github.com/grepplabs/kafka-proxy/plugin/local-auth-scram/protob\x06proto3"

var (
	file_scram_proto_rawDescOnce sync.Once
	file_scram_proto_rawDescData []byte
)

func file_scram_proto_rawDescGZIP() []byte {
	file_scram_proto_rawDescOnce.Do(func() {
		file_scram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scram_proto_rawDesc), len(file_scram_proto_rawDesc)))
	})
	return file_scram_proto_rawDescData
}

var file_scram_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_scram_proto_goTypes = []any{
	(*LoadCredentialRequest)(nil), // 0: proto.LoadCredentialRequest
	(*GetCredentialResponse)(nil), // 1: proto.GetCredentialResponse
}
var file_scram_proto_depIdxs = []int32{
	0, // 0: proto.ScramAuthenticator.GetCredential:input_type -> proto.LoadCredentialRequest
	1, // 1: proto.ScramAuthenticator.GetCredential:output_type -> proto.GetCredentialResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scram_proto_init() }
func file_scram_proto_init() {
	if File_scram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scram_proto_rawDesc), len(file_scram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scram_proto_goTypes,
		DependencyIndexes: file_scram_proto_depIdxs,
		MessageInfos:      file_scram_proto_msgTypes,
	}.Build()
	File_scram_proto = out.File
	file_scram_proto_goTypes = nil
	file_scram_proto_depIdxs = nil
}
